definition:
  short_name: prometheus
  name: Prometheus
  description: Coralogix allows you to monitor Prometheus events through webhooks. Using Alertmanager, you can track the state of instances and machines, monitor their memory, disk usage and more. Using alerts and visualizations you can gain insight into the status of these Alerts.  This can help with root cause and impact analysis as well as in correlating resources with issues.
  icon_details:
    light: "assets/integrations/prometheus.svg"
  tags:
    - Push
    - Prometheus
  details:
    - name: Prometheus
      url: https://coralogix.com/docs/prometheus-alertmanager/
revisions:
  - revision: 0.0.1
    field_definitions: v0.0.1/fields.yaml
    template:
      type: ManagedService
