changes:
  - version: 0.12.1
    description_md: |
      ### Fix:
      * Remove `k8s.pod.name`, `k8s.job.name` and `k8s.node.name` from subsystem attribute list ([#30](https://github.com/coralogix/monitoring-shippers/pull/30))
      * Add tolerations ([#30](https://github.com/coralogix/monitoring-shippers/pull/30))
