definition:
  short_name: K8s-Collector
  name: Kubernetes Infrastructure Monitoring
  description: | 
    For simple and easy automated installation of the <a href='https://coralogix.com/docs/kubernetes-dashboard/'>Kubernetes Dashboard</a>, Coralogix offers Kubernetes Infrastructure Monitoring. With this feature, the exact data needed for installation - node, pod and cluster metrics, as well as k8s events - is located and installed via our pre-configured OpenTelemetry Collector, without the need to manually install each different component.
  icon_details:
    light: "/assets/integrations/k8s.svg"
  tags:
    - Kubernetes
    - OpenTelemetry
    - Infrastructure
    - Helm
  details:
    - name: the Kubernetes Infrastructure Monitoring
      url: https://coralogix.com/docs/kubernetes-collector/
    - name: the Kubernetes Dashboard
      url: https://coralogix.com/docs/kubernetes-dashboard/
  changelog:
    type: Local
    path: changelog.yaml
revisions:
  - revision: 0.0.1
    template:
      type: HelmChart
      helm_chart_values: v0.0.1/values.yaml
      commands: v0.0.1/commands.yaml
      integration_guide: v0.0.1/integration_guide.yaml
    field_definitions: v0.0.1/fields.yaml
  - revision: 0.12.1
    template:
      type: HelmChart
      helm_chart_values: v0.12.1/values.yaml
      commands: v0.12.1/commands.yaml
      integration_guide: v0.12.1/integration_guide.yaml
    field_definitions: v0.12.1/fields.yaml
