name: Terraform Testing

on:
  push:
    
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ env.packages }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: upload
        run: zip -r -q integrations.zip integrations
      - name: ls
        run: ls
