name: coralogix-aws-shipper tests
on:
  workflow_run:
    workflows: ["test2"]
    types:
      - completed
  push:
    paths:
      - 'README.md'
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: run
        run: echo 1
              
      
