name: Synchronizing Cloudformation repo with serverless

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - main
  # push:
  #     branches: [master, main]

jobs:
  Get-matrix:
    runs-on: ubuntu-latest
    env:
      branch_name: ${{ github.event.inputs.branch_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/checkout@v4
        id: checkout
        with:
          repository: coralogix/aws-lambda-integration-tests
          token: ${{ secrets.DESTINATION_REPO_TOKEN }}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: run test
        run: | 
          ls
          ./deploy_code.sh sar https://github.com/coralogix/coralogix-aws-shipper.git master
