name: test2
on:
  push:
    # branches:
    #   - master
    # paths:
    #   - 'meta.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: echo $(1/0)
      
              
      
